#!MANAGED-CONFIG $subs_link interval=43200 strict=true
# Surge nodes-only profile

[General]
loglevel = notify
dns-server = 223.5.5.5, 1.1.1.1
skip-proxy = localhost, *.local, 127.0.0.1/8, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
proxy-test-url = http://www.gstatic.com/generate_204

[Panel]
SubscribeInfo = $subscribe_info, style=info

[Proxy]
$proxies

[Proxy Group]
PROXY = select, $proxy_group
♻️ 自动选择 = url-test, $proxy_group, url=http://www.gstatic.com/generate_204, interval=300

[Rule]
DOMAIN,$subs_domain,DIRECT
GEOIP,CN,DIRECT
FINAL,PROXY
