# Quantumult X nodes-only

[general]
server_check_url=https://www.gstatic.com/generate_204

[dns]
server=223.5.5.5
server=1.1.1.1

[policy]
static=PROXY, $proxy_group
url-latency-benchmark=♻️ 自动选择, $proxy_group, check-interval=600, tolerance=0

[server_local]
$proxies

[filter_local]
host, $subs_domain, direct
final, PROXY
