# Quantumult X simple profile（无远程 filter URL）

[general]
server_check_url=https://www.gstatic.com/generate_204

[dns]
server=223.5.5.5
server=114.114.114.114

[policy]
static=🏠 回国, $proxy_group_cn, direct
static=🚀 节点选择, ♻️ 自动选择, direct
url-latency-benchmark=♻️ 自动选择, $proxy_group_intl, check-interval=600, tolerance=0
static=🛑 广告拦截, reject, direct, 🚀 节点选择
static=🎯 全球直连, 🏠 回国, direct, 🚀 节点选择
static=🐟 漏网之鱼, 🚀 节点选择, ♻️ 自动选择, direct

[server_local]
$proxies

[filter_local]
host, $subs_domain, direct
host-suffix, doubleclick.net, reject
host-suffix, googlesyndication.com, reject
host-suffix, cn, 🏠 回国
geoip, cn, 🏠 回国
final, 🐟 漏网之鱼
